// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2XKXPVrlGU8MPwweLNJx9aom9nsEtJl0',
    appId: '1:299038856875:web:491bfc74716f7c65f589ee',
    messagingSenderId: '299038856875',
    projectId: 'ditonton-aldi',
    authDomain: 'ditonton-aldi.firebaseapp.com',
    storageBucket: 'ditonton-aldi.firebasestorage.app',
    measurementId: 'G-8E4NK8DDWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY4qSFtInsGbrH9kofv5p13yQwCNkJLno',
    appId: '1:299038856875:android:3e0dc35eba4d4bf9f589ee',
    messagingSenderId: '299038856875',
    projectId: 'ditonton-aldi',
    storageBucket: 'ditonton-aldi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Wyd8Ar0KR-Hp_Q1NKKo_Ypr9ega4PHk',
    appId: '1:299038856875:ios:b936c97c8f6d8367f589ee',
    messagingSenderId: '299038856875',
    projectId: 'ditonton-aldi',
    storageBucket: 'ditonton-aldi.firebasestorage.app',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
