// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton/test/presentation/pages/home_movie_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:ditonton/domain/usecases/movie/get_now_playing_movies.dart'
    as _i2;
import 'package:ditonton/domain/usecases/movie/get_popular_movies.dart' as _i3;
import 'package:ditonton/domain/usecases/movie/get_top_rated_movies.dart'
    as _i4;
import 'package:ditonton/domain/usecases/movie/search_movies.dart' as _i6;
import 'package:ditonton/presentation/bloc/movie/movie_list_cubit.dart' as _i8;
import 'package:ditonton/presentation/bloc/movie/movie_list_state.dart' as _i5;
import 'package:ditonton/presentation/bloc/movie/movie_search_cubit.dart'
    as _i11;
import 'package:ditonton/presentation/bloc/movie/movie_search_state.dart'
    as _i7;
import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetNowPlayingMovies_0 extends _i1.SmartFake
    implements _i2.GetNowPlayingMovies {
  _FakeGetNowPlayingMovies_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularMovies_1 extends _i1.SmartFake
    implements _i3.GetPopularMovies {
  _FakeGetPopularMovies_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedMovies_2 extends _i1.SmartFake
    implements _i4.GetTopRatedMovies {
  _FakeGetTopRatedMovies_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieListState_3 extends _i1.SmartFake
    implements _i5.MovieListState {
  _FakeMovieListState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchMovies_4 extends _i1.SmartFake implements _i6.SearchMovies {
  _FakeSearchMovies_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieSearchState_5 extends _i1.SmartFake
    implements _i7.MovieSearchState {
  _FakeMovieSearchState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieListCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieListCubit extends _i1.Mock implements _i8.MovieListCubit {
  @override
  _i2.GetNowPlayingMovies get getNowPlayingMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getNowPlayingMovies),
            returnValue: _FakeGetNowPlayingMovies_0(
              this,
              Invocation.getter(#getNowPlayingMovies),
            ),
            returnValueForMissingStub: _FakeGetNowPlayingMovies_0(
              this,
              Invocation.getter(#getNowPlayingMovies),
            ),
          )
          as _i2.GetNowPlayingMovies);

  @override
  _i3.GetPopularMovies get getPopularMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularMovies),
            returnValue: _FakeGetPopularMovies_1(
              this,
              Invocation.getter(#getPopularMovies),
            ),
            returnValueForMissingStub: _FakeGetPopularMovies_1(
              this,
              Invocation.getter(#getPopularMovies),
            ),
          )
          as _i3.GetPopularMovies);

  @override
  _i4.GetTopRatedMovies get getTopRatedMovies =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedMovies),
            returnValue: _FakeGetTopRatedMovies_2(
              this,
              Invocation.getter(#getTopRatedMovies),
            ),
            returnValueForMissingStub: _FakeGetTopRatedMovies_2(
              this,
              Invocation.getter(#getTopRatedMovies),
            ),
          )
          as _i4.GetTopRatedMovies);

  @override
  _i5.MovieListState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMovieListState_3(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeMovieListState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.MovieListState);

  @override
  _i9.Stream<_i5.MovieListState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i5.MovieListState>.empty(),
            returnValueForMissingStub: _i9.Stream<_i5.MovieListState>.empty(),
          )
          as _i9.Stream<_i5.MovieListState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i9.Future<void> fetchNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#fetchNowPlayingMovies, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> fetchPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPopularMovies, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> fetchTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTopRatedMovies, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<void> fetchAll() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAll, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void emit(_i5.MovieListState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i10.Change<_i5.MovieListState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}

/// A class which mocks [MovieSearchCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieSearchCubit extends _i1.Mock implements _i11.MovieSearchCubit {
  @override
  _i6.SearchMovies get searchMovies =>
      (super.noSuchMethod(
            Invocation.getter(#searchMovies),
            returnValue: _FakeSearchMovies_4(
              this,
              Invocation.getter(#searchMovies),
            ),
            returnValueForMissingStub: _FakeSearchMovies_4(
              this,
              Invocation.getter(#searchMovies),
            ),
          )
          as _i6.SearchMovies);

  @override
  _i7.MovieSearchState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMovieSearchState_5(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeMovieSearchState_5(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i7.MovieSearchState);

  @override
  _i9.Stream<_i7.MovieSearchState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i7.MovieSearchState>.empty(),
            returnValueForMissingStub: _i9.Stream<_i7.MovieSearchState>.empty(),
          )
          as _i9.Stream<_i7.MovieSearchState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i9.Future<void> fetchMovieSearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMovieSearch, [query]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void clearSearch() => super.noSuchMethod(
    Invocation.method(#clearSearch, []),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i7.MovieSearchState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i10.Change<_i7.MovieSearchState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);
}
