// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton/test/presentation/pages/movie_detail_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;

import 'package:ditonton/common/failure.dart' as _i14;
import 'package:ditonton/domain/entities/movie.dart' as _i16;
import 'package:ditonton/domain/entities/movie_detail.dart' as _i11;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i8;
import 'package:ditonton/domain/usecases/movie/get_movie_detail.dart' as _i2;
import 'package:ditonton/domain/usecases/movie/get_movie_recommendations.dart'
    as _i3;
import 'package:ditonton/domain/usecases/movie/get_watchlist_status.dart'
    as _i4;
import 'package:ditonton/domain/usecases/movie/remove_watchlist.dart' as _i6;
import 'package:ditonton/domain/usecases/movie/save_watchlist.dart' as _i5;
import 'package:ditonton/presentation/bloc/movie/movie_detail_cubit.dart'
    as _i9;
import 'package:ditonton/presentation/bloc/movie/movie_detail_state.dart'
    as _i7;
import 'package:flutter_bloc/flutter_bloc.dart' as _i12;
import 'package:fpdart/fpdart.dart' as _i13;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetMovieDetail_0 extends _i1.SmartFake
    implements _i2.GetMovieDetail {
  _FakeGetMovieDetail_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetMovieRecommendations_1 extends _i1.SmartFake
    implements _i3.GetMovieRecommendations {
  _FakeGetMovieRecommendations_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetWatchListStatus_2 extends _i1.SmartFake
    implements _i4.GetWatchListStatus {
  _FakeGetWatchListStatus_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaveWatchlist_3 extends _i1.SmartFake implements _i5.SaveWatchlist {
  _FakeSaveWatchlist_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoveWatchlist_4 extends _i1.SmartFake
    implements _i6.RemoveWatchlist {
  _FakeRemoveWatchlist_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDetailState_5 extends _i1.SmartFake
    implements _i7.MovieDetailState {
  _FakeMovieDetailState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieRepository_6 extends _i1.SmartFake
    implements _i8.MovieRepository {
  _FakeMovieRepository_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieDetailCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailCubit extends _i1.Mock implements _i9.MovieDetailCubit {
  @override
  _i2.GetMovieDetail get getMovieDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getMovieDetail),
            returnValue: _FakeGetMovieDetail_0(
              this,
              Invocation.getter(#getMovieDetail),
            ),
            returnValueForMissingStub: _FakeGetMovieDetail_0(
              this,
              Invocation.getter(#getMovieDetail),
            ),
          )
          as _i2.GetMovieDetail);

  @override
  _i3.GetMovieRecommendations get getMovieRecommendations =>
      (super.noSuchMethod(
            Invocation.getter(#getMovieRecommendations),
            returnValue: _FakeGetMovieRecommendations_1(
              this,
              Invocation.getter(#getMovieRecommendations),
            ),
            returnValueForMissingStub: _FakeGetMovieRecommendations_1(
              this,
              Invocation.getter(#getMovieRecommendations),
            ),
          )
          as _i3.GetMovieRecommendations);

  @override
  _i4.GetWatchListStatus get getWatchListStatus =>
      (super.noSuchMethod(
            Invocation.getter(#getWatchListStatus),
            returnValue: _FakeGetWatchListStatus_2(
              this,
              Invocation.getter(#getWatchListStatus),
            ),
            returnValueForMissingStub: _FakeGetWatchListStatus_2(
              this,
              Invocation.getter(#getWatchListStatus),
            ),
          )
          as _i4.GetWatchListStatus);

  @override
  _i5.SaveWatchlist get saveWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#saveWatchlist),
            returnValue: _FakeSaveWatchlist_3(
              this,
              Invocation.getter(#saveWatchlist),
            ),
            returnValueForMissingStub: _FakeSaveWatchlist_3(
              this,
              Invocation.getter(#saveWatchlist),
            ),
          )
          as _i5.SaveWatchlist);

  @override
  _i6.RemoveWatchlist get removeWatchlist =>
      (super.noSuchMethod(
            Invocation.getter(#removeWatchlist),
            returnValue: _FakeRemoveWatchlist_4(
              this,
              Invocation.getter(#removeWatchlist),
            ),
            returnValueForMissingStub: _FakeRemoveWatchlist_4(
              this,
              Invocation.getter(#removeWatchlist),
            ),
          )
          as _i6.RemoveWatchlist);

  @override
  _i7.MovieDetailState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeMovieDetailState_5(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeMovieDetailState_5(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i7.MovieDetailState);

  @override
  _i10.Stream<_i7.MovieDetailState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i10.Stream<_i7.MovieDetailState>.empty(),
            returnValueForMissingStub:
                _i10.Stream<_i7.MovieDetailState>.empty(),
          )
          as _i10.Stream<_i7.MovieDetailState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.Future<void> fetchMovieDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchMovieDetail, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> addWatchlist(_i11.MovieDetail? movie) =>
      (super.noSuchMethod(
            Invocation.method(#addWatchlist, [movie]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> removeFromWatchlist(_i11.MovieDetail? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromWatchlist, [movie]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  _i10.Future<void> loadWatchlistStatus(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#loadWatchlistStatus, [id]),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void emit(_i7.MovieDetailState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i12.Change<_i7.MovieDetailState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i10.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);
}

/// A class which mocks [GetMovieDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieDetail extends _i1.Mock implements _i2.GetMovieDetail {
  MockGetMovieDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i8.MovieRepository);

  @override
  _i10.Future<_i13.Either<_i14.Failure, _i11.MovieDetail>> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i10.Future<_i13.Either<_i14.Failure, _i11.MovieDetail>>.value(
                  _i15.dummyValue<_i13.Either<_i14.Failure, _i11.MovieDetail>>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i10.Future<_i13.Either<_i14.Failure, _i11.MovieDetail>>);
}

/// A class which mocks [GetMovieRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMovieRecommendations extends _i1.Mock
    implements _i3.GetMovieRecommendations {
  MockGetMovieRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i8.MovieRepository);

  @override
  _i10.Future<_i13.Either<_i14.Failure, List<_i16.Movie>>> execute(
    dynamic id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue:
                _i10.Future<_i13.Either<_i14.Failure, List<_i16.Movie>>>.value(
                  _i15.dummyValue<_i13.Either<_i14.Failure, List<_i16.Movie>>>(
                    this,
                    Invocation.method(#execute, [id]),
                  ),
                ),
          )
          as _i10.Future<_i13.Either<_i14.Failure, List<_i16.Movie>>>);
}

/// A class which mocks [GetWatchListStatus].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatus extends _i1.Mock
    implements _i4.GetWatchListStatus {
  MockGetWatchListStatus() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i8.MovieRepository);

  @override
  _i10.Future<bool> execute(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [id]),
            returnValue: _i10.Future<bool>.value(false),
          )
          as _i10.Future<bool>);
}

/// A class which mocks [SaveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlist extends _i1.Mock implements _i5.SaveWatchlist {
  MockSaveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i8.MovieRepository);

  @override
  _i10.Future<_i13.Either<_i14.Failure, String>> execute(
    _i11.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [movie]),
            returnValue: _i10.Future<_i13.Either<_i14.Failure, String>>.value(
              _i15.dummyValue<_i13.Either<_i14.Failure, String>>(
                this,
                Invocation.method(#execute, [movie]),
              ),
            ),
          )
          as _i10.Future<_i13.Either<_i14.Failure, String>>);
}

/// A class which mocks [RemoveWatchlist].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlist extends _i1.Mock implements _i6.RemoveWatchlist {
  MockRemoveWatchlist() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.MovieRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeMovieRepository_6(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i8.MovieRepository);

  @override
  _i10.Future<_i13.Either<_i14.Failure, String>> execute(
    _i11.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [movie]),
            returnValue: _i10.Future<_i13.Either<_i14.Failure, String>>.value(
              _i15.dummyValue<_i13.Either<_i14.Failure, String>>(
                this,
                Invocation.method(#execute, [movie]),
              ),
            ),
          )
          as _i10.Future<_i13.Either<_i14.Failure, String>>);
}
