// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton/test/presentation/pages/tv_series_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:ditonton/domain/usecases/tv_series/get_now_playing_tv_series.dart'
    as _i2;
import 'package:ditonton/domain/usecases/tv_series/get_popular_tv_series.dart'
    as _i3;
import 'package:ditonton/domain/usecases/tv_series/get_top_rated_tv_series.dart'
    as _i4;
import 'package:ditonton/domain/usecases/tv_series/search_tv_series.dart'
    as _i6;
import 'package:ditonton/presentation/bloc/tv_series/tv_series_list_cubit.dart'
    as _i5;
import 'package:ditonton/presentation/bloc/tv_series/tv_series_search_cubit.dart'
    as _i7;
import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetNowPlayingTvSeries_0 extends _i1.SmartFake
    implements _i2.GetNowPlayingTvSeries {
  _FakeGetNowPlayingTvSeries_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetPopularTvSeries_1 extends _i1.SmartFake
    implements _i3.GetPopularTvSeries {
  _FakeGetPopularTvSeries_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopRatedTvSeries_2 extends _i1.SmartFake
    implements _i4.GetTopRatedTvSeries {
  _FakeGetTopRatedTvSeries_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvSeriesListState_3 extends _i1.SmartFake
    implements _i5.TvSeriesListState {
  _FakeTvSeriesListState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSearchTvSeries_4 extends _i1.SmartFake
    implements _i6.SearchTvSeries {
  _FakeSearchTvSeries_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvSeriesSearchState_5 extends _i1.SmartFake
    implements _i7.TvSeriesSearchState {
  _FakeTvSeriesSearchState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TvSeriesListCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesListCubit extends _i1.Mock implements _i5.TvSeriesListCubit {
  @override
  _i2.GetNowPlayingTvSeries get getNowPlayingTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#getNowPlayingTvSeries),
            returnValue: _FakeGetNowPlayingTvSeries_0(
              this,
              Invocation.getter(#getNowPlayingTvSeries),
            ),
            returnValueForMissingStub: _FakeGetNowPlayingTvSeries_0(
              this,
              Invocation.getter(#getNowPlayingTvSeries),
            ),
          )
          as _i2.GetNowPlayingTvSeries);

  @override
  _i3.GetPopularTvSeries get getPopularTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#getPopularTvSeries),
            returnValue: _FakeGetPopularTvSeries_1(
              this,
              Invocation.getter(#getPopularTvSeries),
            ),
            returnValueForMissingStub: _FakeGetPopularTvSeries_1(
              this,
              Invocation.getter(#getPopularTvSeries),
            ),
          )
          as _i3.GetPopularTvSeries);

  @override
  _i4.GetTopRatedTvSeries get getTopRatedTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#getTopRatedTvSeries),
            returnValue: _FakeGetTopRatedTvSeries_2(
              this,
              Invocation.getter(#getTopRatedTvSeries),
            ),
            returnValueForMissingStub: _FakeGetTopRatedTvSeries_2(
              this,
              Invocation.getter(#getTopRatedTvSeries),
            ),
          )
          as _i4.GetTopRatedTvSeries);

  @override
  _i5.TvSeriesListState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTvSeriesListState_3(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeTvSeriesListState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.TvSeriesListState);

  @override
  _i8.Stream<_i5.TvSeriesListState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i5.TvSeriesListState>.empty(),
            returnValueForMissingStub:
                _i8.Stream<_i5.TvSeriesListState>.empty(),
          )
          as _i8.Stream<_i5.TvSeriesListState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<void> fetchNowPlayingTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#fetchNowPlayingTvSeries, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> fetchPopularTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#fetchPopularTvSeries, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> fetchTopRatedTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#fetchTopRatedTvSeries, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> fetchAll() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAll, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void emit(_i5.TvSeriesListState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i9.Change<_i5.TvSeriesListState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [TvSeriesSearchCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesSearchCubit extends _i1.Mock
    implements _i7.TvSeriesSearchCubit {
  @override
  _i6.SearchTvSeries get searchTvSeries =>
      (super.noSuchMethod(
            Invocation.getter(#searchTvSeries),
            returnValue: _FakeSearchTvSeries_4(
              this,
              Invocation.getter(#searchTvSeries),
            ),
            returnValueForMissingStub: _FakeSearchTvSeries_4(
              this,
              Invocation.getter(#searchTvSeries),
            ),
          )
          as _i6.SearchTvSeries);

  @override
  _i7.TvSeriesSearchState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeTvSeriesSearchState_5(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeTvSeriesSearchState_5(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i7.TvSeriesSearchState);

  @override
  _i8.Stream<_i7.TvSeriesSearchState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i8.Stream<_i7.TvSeriesSearchState>.empty(),
            returnValueForMissingStub:
                _i8.Stream<_i7.TvSeriesSearchState>.empty(),
          )
          as _i8.Stream<_i7.TvSeriesSearchState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<void> fetchTvSeriesSearch(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTvSeriesSearch, [query]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void clearSearch() => super.noSuchMethod(
    Invocation.method(#clearSearch, []),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i7.TvSeriesSearchState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i9.Change<_i7.TvSeriesSearchState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
