// Mocks generated by Mockito 5.4.6 from annotations
// in ditonton/test/helpers/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i25;
import 'dart:typed_data' as _i26;

import 'package:ditonton/common/failure.dart' as _i8;
import 'package:ditonton/data/datasources/db/database_helper.dart' as _i23;
import 'package:ditonton/data/datasources/movie_local_data_source.dart' as _i17;
import 'package:ditonton/data/datasources/movie_remote_data_source.dart'
    as _i15;
import 'package:ditonton/data/datasources/tv_series_local_data_source.dart'
    as _i21;
import 'package:ditonton/data/datasources/tv_series_remote_data_source.dart'
    as _i19;
import 'package:ditonton/data/models/movie_detail_model.dart' as _i2;
import 'package:ditonton/data/models/movie_model.dart' as _i16;
import 'package:ditonton/data/models/movie_table.dart' as _i18;
import 'package:ditonton/data/models/tv_series_detail_model.dart' as _i3;
import 'package:ditonton/data/models/tv_series_model.dart' as _i20;
import 'package:ditonton/data/models/tv_series_table.dart' as _i22;
import 'package:ditonton/domain/entities/movie.dart' as _i9;
import 'package:ditonton/domain/entities/movie_detail.dart' as _i11;
import 'package:ditonton/domain/entities/tv_series.dart' as _i13;
import 'package:ditonton/domain/entities/tv_series_detail.dart' as _i14;
import 'package:ditonton/domain/repositories/movie_repository.dart' as _i5;
import 'package:ditonton/domain/repositories/tv_series_repository.dart' as _i12;
import 'package:fpdart/fpdart.dart' as _i7;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:sqflite/sqflite.dart' as _i24;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMovieDetailResponse_0 extends _i1.SmartFake
    implements _i2.MovieDetailResponse {
  _FakeMovieDetailResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTvSeriesDetailResponse_1 extends _i1.SmartFake
    implements _i3.TvSeriesDetailResponse {
  _FakeTvSeriesDetailResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2 extends _i1.SmartFake implements _i4.Response {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_3 extends _i1.SmartFake
    implements _i4.StreamedResponse {
  _FakeStreamedResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i5.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>> getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue:
                _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _i10.dummyValue<_i7.Either<_i8.Failure, List<_i9.Movie>>>(
                    this,
                    Invocation.method(#getNowPlayingMovies, []),
                  ),
                ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>>);

  @override
  _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue:
                _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _i10.dummyValue<_i7.Either<_i8.Failure, List<_i9.Movie>>>(
                    this,
                    Invocation.method(#getPopularMovies, []),
                  ),
                ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>>);

  @override
  _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue:
                _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _i10.dummyValue<_i7.Either<_i8.Failure, List<_i9.Movie>>>(
                    this,
                    Invocation.method(#getTopRatedMovies, []),
                  ),
                ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>>);

  @override
  _i6.Future<_i7.Either<_i8.Failure, _i11.MovieDetail>> getMovieDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue:
                _i6.Future<_i7.Either<_i8.Failure, _i11.MovieDetail>>.value(
                  _i10.dummyValue<_i7.Either<_i8.Failure, _i11.MovieDetail>>(
                    this,
                    Invocation.method(#getMovieDetail, [id]),
                  ),
                ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, _i11.MovieDetail>>);

  @override
  _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>> getMovieRecommendations(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue:
                _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _i10.dummyValue<_i7.Either<_i8.Failure, List<_i9.Movie>>>(
                    this,
                    Invocation.method(#getMovieRecommendations, [id]),
                  ),
                ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>>);

  @override
  _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>> searchMovies(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue:
                _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _i10.dummyValue<_i7.Either<_i8.Failure, List<_i9.Movie>>>(
                    this,
                    Invocation.method(#searchMovies, [query]),
                  ),
                ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>>);

  @override
  _i6.Future<_i7.Either<_i8.Failure, String>> saveWatchlist(
    _i11.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [movie]),
            returnValue: _i6.Future<_i7.Either<_i8.Failure, String>>.value(
              _i10.dummyValue<_i7.Either<_i8.Failure, String>>(
                this,
                Invocation.method(#saveWatchlist, [movie]),
              ),
            ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, String>>);

  @override
  _i6.Future<_i7.Either<_i8.Failure, String>> removeWatchlist(
    _i11.MovieDetail? movie,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i6.Future<_i7.Either<_i8.Failure, String>>.value(
              _i10.dummyValue<_i7.Either<_i8.Failure, String>>(
                this,
                Invocation.method(#removeWatchlist, [movie]),
              ),
            ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, String>>);

  @override
  _i6.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue:
                _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>>.value(
                  _i10.dummyValue<_i7.Either<_i8.Failure, List<_i9.Movie>>>(
                    this,
                    Invocation.method(#getWatchlistMovies, []),
                  ),
                ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, List<_i9.Movie>>>);
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i12.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>
  getAiringTodayTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getAiringTodayTvSeries, []),
            returnValue:
                _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>.value(
                  _i10.dummyValue<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>(
                    this,
                    Invocation.method(#getAiringTodayTvSeries, []),
                  ),
                ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>);

  @override
  _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>
  getPopularTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvSeries, []),
            returnValue:
                _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>.value(
                  _i10.dummyValue<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>(
                    this,
                    Invocation.method(#getPopularTvSeries, []),
                  ),
                ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>);

  @override
  _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>
  getTopRatedTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTvSeries, []),
            returnValue:
                _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>.value(
                  _i10.dummyValue<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>(
                    this,
                    Invocation.method(#getTopRatedTvSeries, []),
                  ),
                ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>);

  @override
  _i6.Future<_i7.Either<_i8.Failure, _i14.TvSeriesDetail>> getTvSeriesDetail(
    int? id,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesDetail, [id]),
            returnValue:
                _i6.Future<_i7.Either<_i8.Failure, _i14.TvSeriesDetail>>.value(
                  _i10.dummyValue<_i7.Either<_i8.Failure, _i14.TvSeriesDetail>>(
                    this,
                    Invocation.method(#getTvSeriesDetail, [id]),
                  ),
                ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, _i14.TvSeriesDetail>>);

  @override
  _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>
  getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesRecommendations, [id]),
            returnValue:
                _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>.value(
                  _i10.dummyValue<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>(
                    this,
                    Invocation.method(#getTvSeriesRecommendations, [id]),
                  ),
                ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>);

  @override
  _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>> searchTvSeries(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvSeries, [query]),
            returnValue:
                _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>.value(
                  _i10.dummyValue<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>(
                    this,
                    Invocation.method(#searchTvSeries, [query]),
                  ),
                ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>);

  @override
  _i6.Future<_i7.Either<_i8.Failure, String>> saveWatchlist(
    _i14.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveWatchlist, [tvSeries]),
            returnValue: _i6.Future<_i7.Either<_i8.Failure, String>>.value(
              _i10.dummyValue<_i7.Either<_i8.Failure, String>>(
                this,
                Invocation.method(#saveWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, String>>);

  @override
  _i6.Future<_i7.Either<_i8.Failure, String>> removeWatchlist(
    _i14.TvSeriesDetail? tvSeries,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [tvSeries]),
            returnValue: _i6.Future<_i7.Either<_i8.Failure, String>>.value(
              _i10.dummyValue<_i7.Either<_i8.Failure, String>>(
                this,
                Invocation.method(#removeWatchlist, [tvSeries]),
              ),
            ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, String>>);

  @override
  _i6.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#isAddedToWatchlist, [id]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>
  getWatchlistTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTvSeries, []),
            returnValue:
                _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>.value(
                  _i10.dummyValue<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>(
                    this,
                    Invocation.method(#getWatchlistTvSeries, []),
                  ),
                ),
          )
          as _i6.Future<_i7.Either<_i8.Failure, List<_i13.TvSeries>>>);
}

/// A class which mocks [MovieRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRemoteDataSource extends _i1.Mock
    implements _i15.MovieRemoteDataSource {
  MockMovieRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i16.MovieModel>> getNowPlayingMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getNowPlayingMovies, []),
            returnValue: _i6.Future<List<_i16.MovieModel>>.value(
              <_i16.MovieModel>[],
            ),
          )
          as _i6.Future<List<_i16.MovieModel>>);

  @override
  _i6.Future<List<_i16.MovieModel>> getPopularMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, []),
            returnValue: _i6.Future<List<_i16.MovieModel>>.value(
              <_i16.MovieModel>[],
            ),
          )
          as _i6.Future<List<_i16.MovieModel>>);

  @override
  _i6.Future<List<_i16.MovieModel>> getTopRatedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedMovies, []),
            returnValue: _i6.Future<List<_i16.MovieModel>>.value(
              <_i16.MovieModel>[],
            ),
          )
          as _i6.Future<List<_i16.MovieModel>>);

  @override
  _i6.Future<_i2.MovieDetailResponse> getMovieDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetail, [id]),
            returnValue: _i6.Future<_i2.MovieDetailResponse>.value(
              _FakeMovieDetailResponse_0(
                this,
                Invocation.method(#getMovieDetail, [id]),
              ),
            ),
          )
          as _i6.Future<_i2.MovieDetailResponse>);

  @override
  _i6.Future<List<_i16.MovieModel>> getMovieRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieRecommendations, [id]),
            returnValue: _i6.Future<List<_i16.MovieModel>>.value(
              <_i16.MovieModel>[],
            ),
          )
          as _i6.Future<List<_i16.MovieModel>>);

  @override
  _i6.Future<List<_i16.MovieModel>> searchMovies(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query]),
            returnValue: _i6.Future<List<_i16.MovieModel>>.value(
              <_i16.MovieModel>[],
            ),
          )
          as _i6.Future<List<_i16.MovieModel>>);
}

/// A class which mocks [MovieLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieLocalDataSource extends _i1.Mock
    implements _i17.MovieLocalDataSource {
  MockMovieLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> insertWatchlist(_i18.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [movie]),
            returnValue: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlist, [movie]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> removeWatchlist(_i18.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlist, [movie]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i18.MovieTable?> getMovieById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieById, [id]),
            returnValue: _i6.Future<_i18.MovieTable?>.value(),
          )
          as _i6.Future<_i18.MovieTable?>);

  @override
  _i6.Future<List<_i18.MovieTable>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue: _i6.Future<List<_i18.MovieTable>>.value(
              <_i18.MovieTable>[],
            ),
          )
          as _i6.Future<List<_i18.MovieTable>>);
}

/// A class which mocks [TvSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRemoteDataSource extends _i1.Mock
    implements _i19.TvSeriesRemoteDataSource {
  MockTvSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i20.TvSeriesModel>> getAiringTodayTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getAiringTodayTvSeries, []),
            returnValue: _i6.Future<List<_i20.TvSeriesModel>>.value(
              <_i20.TvSeriesModel>[],
            ),
          )
          as _i6.Future<List<_i20.TvSeriesModel>>);

  @override
  _i6.Future<List<_i20.TvSeriesModel>> getPopularTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getPopularTvSeries, []),
            returnValue: _i6.Future<List<_i20.TvSeriesModel>>.value(
              <_i20.TvSeriesModel>[],
            ),
          )
          as _i6.Future<List<_i20.TvSeriesModel>>);

  @override
  _i6.Future<List<_i20.TvSeriesModel>> getTopRatedTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getTopRatedTvSeries, []),
            returnValue: _i6.Future<List<_i20.TvSeriesModel>>.value(
              <_i20.TvSeriesModel>[],
            ),
          )
          as _i6.Future<List<_i20.TvSeriesModel>>);

  @override
  _i6.Future<_i3.TvSeriesDetailResponse> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesDetail, [id]),
            returnValue: _i6.Future<_i3.TvSeriesDetailResponse>.value(
              _FakeTvSeriesDetailResponse_1(
                this,
                Invocation.method(#getTvSeriesDetail, [id]),
              ),
            ),
          )
          as _i6.Future<_i3.TvSeriesDetailResponse>);

  @override
  _i6.Future<List<_i20.TvSeriesModel>> getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesRecommendations, [id]),
            returnValue: _i6.Future<List<_i20.TvSeriesModel>>.value(
              <_i20.TvSeriesModel>[],
            ),
          )
          as _i6.Future<List<_i20.TvSeriesModel>>);

  @override
  _i6.Future<List<_i20.TvSeriesModel>> searchTvSeries(String? query) =>
      (super.noSuchMethod(
            Invocation.method(#searchTvSeries, [query]),
            returnValue: _i6.Future<List<_i20.TvSeriesModel>>.value(
              <_i20.TvSeriesModel>[],
            ),
          )
          as _i6.Future<List<_i20.TvSeriesModel>>);
}

/// A class which mocks [TvSeriesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesLocalDataSource extends _i1.Mock
    implements _i21.TvSeriesLocalDataSource {
  MockTvSeriesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> insertWatchlistTvSeries(_i22.TvSeriesTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlistTvSeries, [movie]),
            returnValue: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#insertWatchlistTvSeries, [movie]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<String> removeWatchlistTvSeries(_i22.TvSeriesTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlistTvSeries, [movie]),
            returnValue: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#removeWatchlistTvSeries, [movie]),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i22.TvSeriesTable?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesById, [id]),
            returnValue: _i6.Future<_i22.TvSeriesTable?>.value(),
          )
          as _i6.Future<_i22.TvSeriesTable?>);

  @override
  _i6.Future<List<_i22.TvSeriesTable>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTvSeries, []),
            returnValue: _i6.Future<List<_i22.TvSeriesTable>>.value(
              <_i22.TvSeriesTable>[],
            ),
          )
          as _i6.Future<List<_i22.TvSeriesTable>>);
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i23.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i24.Database?> get database =>
      (super.noSuchMethod(
            Invocation.getter(#database),
            returnValue: _i6.Future<_i24.Database?>.value(),
          )
          as _i6.Future<_i24.Database?>);

  @override
  _i6.Future<int> insertWatchlist(_i18.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlist, [movie]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> insertWatchlistTvSeries(_i22.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#insertWatchlistTvSeries, [tvSeries]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> removeWatchlist(_i18.MovieTable? movie) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlist, [movie]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<int> removeWatchlistTvSeries(_i22.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(
            Invocation.method(#removeWatchlistTvSeries, [tvSeries]),
            returnValue: _i6.Future<int>.value(0),
          )
          as _i6.Future<int>);

  @override
  _i6.Future<Map<String, dynamic>?> getMovieById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieById, [id]),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<Map<String, dynamic>?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTvSeriesById, [id]),
            returnValue: _i6.Future<Map<String, dynamic>?>.value(),
          )
          as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getWatchlistMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistMovies, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> getWatchlistTvSeries() =>
      (super.noSuchMethod(
            Invocation.method(#getWatchlistTvSeries, []),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i4.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#head, [url], {#headers: headers}),
            returnValue: _i6.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#head, [url], {#headers: headers}),
              ),
            ),
          )
          as _i6.Future<_i4.Response>);

  @override
  _i6.Future<_i4.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url], {#headers: headers}),
            returnValue: _i6.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(#get, [url], {#headers: headers}),
              ),
            ),
          )
          as _i6.Future<_i4.Response>);

  @override
  _i6.Future<_i4.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i6.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #post,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response>);

  @override
  _i6.Future<_i4.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i6.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #put,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response>);

  @override
  _i6.Future<_i4.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i6.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #patch,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response>);

  @override
  _i6.Future<_i4.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i25.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [url],
              {#headers: headers, #body: body, #encoding: encoding},
            ),
            returnValue: _i6.Future<_i4.Response>.value(
              _FakeResponse_2(
                this,
                Invocation.method(
                  #delete,
                  [url],
                  {#headers: headers, #body: body, #encoding: encoding},
                ),
              ),
            ),
          )
          as _i6.Future<_i4.Response>);

  @override
  _i6.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(
            Invocation.method(#read, [url], {#headers: headers}),
            returnValue: _i6.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#read, [url], {#headers: headers}),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<_i26.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readBytes, [url], {#headers: headers}),
            returnValue: _i6.Future<_i26.Uint8List>.value(_i26.Uint8List(0)),
          )
          as _i6.Future<_i26.Uint8List>);

  @override
  _i6.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#send, [request]),
            returnValue: _i6.Future<_i4.StreamedResponse>.value(
              _FakeStreamedResponse_3(
                this,
                Invocation.method(#send, [request]),
              ),
            ),
          )
          as _i6.Future<_i4.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );
}
